version: '2.1'  
services:  
  mariadb:
    build: .
    image: awesomecontainer/wdocker-mariadb:${DOCKERTAG:-latest}
    container_name: mariadb
    volumes:
      - C:\DockerData\mariadb:c:\mariadbdata
    network_mode: nat
    restart: unless-stopped
    ports:
      - 3306:3306
    stdin_open: true